# Generated by Django 2.0.13 on 2019-08-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('calorie', models.FloatField(blank=True, null=True)),
                ('lipid', models.FloatField(blank=True, null=True)),
                ('calcium', models.FloatField(blank=True, null=True)),
                ('vitamina', models.FloatField(blank=True, db_column='vitaminA', null=True)),
                ('vitaminb1', models.FloatField(blank=True, db_column='vitaminB1', null=True)),
                ('vitaminc', models.FloatField(blank=True, db_column='vitaminC', null=True)),
                ('saturated_fatty_acid', models.FloatField(blank=True, null=True)),
                ('protein', models.FloatField(blank=True, null=True)),
                ('carbohydrate', models.FloatField(blank=True, null=True)),
                ('iron', models.FloatField(blank=True, null=True)),
                ('vitamine', models.FloatField(blank=True, db_column='vitaminE', null=True)),
                ('vitaminb2', models.FloatField(blank=True, db_column='vitaminB2', null=True)),
                ('dietary_fiber', models.FloatField(blank=True, null=True)),
                ('salt', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'food_data',
                'managed': False,
            },
        ),
    ]
